# Generated by Django 5.2.7 on 2025-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_approach_road_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landapproachroadattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_attach_approval_report_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landattachapprovalreportattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_co_ordinates_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landcoordinatesattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_key_plan_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landkeyplanattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_location_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landlocationattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_survey_number_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landsurveynumbeattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='land_transmission_line_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landtransmissionlineattachment'),
        ),
        migrations.AlterField(
            model_name='landbankmaster',
            name='lease_deed_file',
            field=models.ManyToManyField(blank=True, null=True, to='land_module.landleasedeedattachment'),
        ),
    ]
