# Generated by Django 5.2.7 on 2025-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0002_alter_landbankmaster_land_approach_road_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landbankmaster',
            name='geo_graphical_cordinates',
        ),
        migrations.RemoveField(
            model_name='landbankmaster',
            name='timeline',
        ),
        migrations.AddField(
            model_name='landbankmaster',
            name='is_land_banck_created',
            field=models.BooleanField(default=False),
        ),
    ]
