# Generated by Django 5.2.7 on 2025-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0003_remove_landbankmaster_geo_graphical_cordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landbankmaster',
            old_name='is_land_banck_created',
            new_name='is_land_bank_created',
        ),
    ]
