# Generated by Django 5.2.7 on 2025-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0004_rename_is_land_banck_created_landbankmaster_is_land_bank_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landbankmaster',
            old_name='new_block_number',
            new_name='block_number',
        ),
        migrations.RenameField(
            model_name='landbankmaster',
            old_name='old_block_number',
            new_name='sale_deed_number',
        ),
        migrations.RenameField(
            model_name='landbankmaster',
            old_name='tcr',
            new_name='tsr',
        ),
        migrations.AddField(
            model_name='landbankmaster',
            name='land_type',
            field=models.CharField(blank=True, choices=[('BUY', 'buy'), ('LEASE', 'lease')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='landbankmaster',
            name='lease_deed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
