# Generated by Django 5.2.7 on 2025-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0005_rename_new_block_number_landbankmaster_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landbankmaster',
            name='is_land_bank_started',
            field=models.BooleanField(default=False),
        ),
    ]
