# Generated by Django 5.2.7 on 2025-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0006_landbankmaster_is_land_bank_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='landbankmaster',
            name='is_land_bank_added_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
