# Generated by Django 5.2.7 on 2025-10-16 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0007_landbankmaster_is_land_bank_added_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landbankmaster',
            name='is_land_bank_approved_by_project_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landbankmaster',
            name='land_bank_approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_bank_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landbankmaster',
            name='land_bank_checked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_bank_checked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landbankmaster',
            name='land_bank_rejected_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_bank_rejected_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
