# Generated by Django 5.2.7 on 2025-10-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0008_landbankmaster_is_land_bank_approved_by_project_hod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landbankmaster',
            old_name='lease_deed_file',
            new_name='land_lease_deed_file',
        ),
    ]
