# Generated by Django 5.2.7 on 2025-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_module', '0010_landrejectedreportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='landbankmaster',
            name='rejected_report_file',
            field=models.ManyToManyField(to='land_module.landrejectedreportattachment'),
        ),
    ]
