# Generated by Django 5.2.7 on 2025-10-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoto_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotodocument',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotodocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoto_module.documentcategory'),
        ),
        migrations.AlterField(
            model_name='hotodocument',
            name='document_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoto_module.document'),
        ),
    ]
