# Generated by Django 5.2.7 on 2025-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoto_module', '0002_hotodocument_is_uploaded_alter_hotodocument_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotodocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
