# Generated by Django 4.2.25 on 2025-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoto_module', '0003_hotodocument_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotodocument',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
