# Generated by Django 4.2.25 on 2025-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoto_module', '0004_alter_hotodocument_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotodocument',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
