# Generated by Django 4.2.25 on 2025-11-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0005_projectassigneduser_project_assigned_users'),
        ('hoto_module', '0005_alter_hotodocument_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedpunchpoints',
            name='punch_point_completed',
        ),
        migrations.RemoveField(
            model_name='punchpointsraise',
            name='closure_date',
        ),
        migrations.RemoveField(
            model_name='punchpointsraise',
            name='hoto',
        ),
        migrations.RemoveField(
            model_name='punchpointsraise',
            name='punch_point_balance',
        ),
        migrations.RemoveField(
            model_name='punchpointsraise',
            name='punch_point_raised',
        ),
        migrations.AddField(
            model_name='completedpunchpoints',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedpunchpoints',
            name='tentative_timeline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punchpointsraise',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='punchpointsraise',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punchpointsraise',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_module.project'),
        ),
    ]
