# Generated by Django 4.2.25 on 2025-11-02 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoto_module', '0006_remove_completedpunchpoints_punch_point_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedRejectedPunchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='accepted_rejected_punch_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='completedpunchpoints',
            old_name='comments',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='completedpunchpoints',
            name='punch_description',
        ),
        migrations.RemoveField(
            model_name='completedpunchpoints',
            name='raise_punch',
        ),
        migrations.RemoveField(
            model_name='completedpunchpoints',
            name='tentative_timeline',
        ),
        migrations.AlterField(
            model_name='completedpunchpoints',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_punch_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcceptedRejectedPunchPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_description', models.TextField(blank=True, null=True)),
                ('tentative_timeline', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('punch_file', models.ManyToManyField(blank=True, to='hoto_module.acceptedrejectedpunchfile')),
                ('raise_punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoto_module.punchpointsraise')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_punch_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='completedpunchpoints',
            name='accepted_rejected_punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoto_module.acceptedrejectedpunchpoints'),
        ),
        migrations.AddField(
            model_name='punchpointsraise',
            name='accepted_rejected_points',
            field=models.ManyToManyField(blank=True, to='hoto_module.acceptedrejectedpunchfile'),
        ),
    ]
