from django.core.management.base import BaseCommand
from hoto_module.models import DocumentCategory, Document

class Command(BaseCommand):
    help = "Add a list of documents with categories to the database"

    def handle(self, *args, **kwargs):
        # Define categories and their documents
        categories_and_documents = {
            "Default": [
                "PLF data for 15 Days (PAT)",
                "Plant ABT meter sealing certificate",
                "Plant ABT meter test report",
                "Module Bar code scanning data / Flash report/Module details",
                "NLDC/SLDC Communication Approval Letter",
                "Civil Drawings- with latest EDL",
                "Plant layout",
                "Individual ICR room layout",
                "MCR room layout",
                "Switch Yard overall Foundation details",
                "Water Tank - Nos, location, capacity, drwg",
                "Culverts- nos, location , capacity, drwg as applicable",
                "Watch tower - nos, location, height, drwg",
                "Roads -  Internal and Peripheral, map, drwg",
                "Array Yard Pile foundation",
                "Walk way and cable tray",
                "Drainage system layout",
                "Firewall",
                "Boundary wall with fencing details",
                "Soil test report",
                "Water test report",
            ],
            "Electrical, Civil and MMS (AC & DC) Drawings- Field & Equipment (MDL)": [
                "All Trench route Map",
                "ICR  Single Line Diagram & Protection SLD",
                "Switchyard Equipment Plan & section layout",
                "HT Cable Route Map",
                "DC cable route map",
                "Plant Flow Diagram (Main Electrical SLD) AC & DC",
                "Cable map (AC, DC other)",
                "Array Layout of the plant",
                "Control diagram sheet",
                "NFPS/NFIPS Drawing",
                "PV Layout",
                "Overall layout",
                "Boundary fencing with fencing layout",
                "Field Earthing and LA layout",
                "Yard Earthing Layout",
                "AC and DC SLD layout",
                "MCS layout",
                "Roads -  Internal and Peripheral, map, drwg",
                "Street light layout",
                "Watch tower - nos, location, height, drwg",
                "Main Gate layout",
                "Yard Equipment foundation layout",
                "Yard Fencing layout",
                "MMS and Module installation layout",
                "MMS GAD",
            ],
            "Manual": [
                "Relays",
                "Transformer (IDT)",
                "Transformer",
                "Aux trafo",
                "Relay Setting data",
                "Relay Setting data for RMU",
                "IOCG Panel relay data",
                "VCB",
                "Battery",
                "Battery charger",
                "LA",
                "Daily,weekly,monthly,annually maintenance plan",
                "Fuses Manual",
                "Operation and Maintenance solar farm manual",
            ],
             "Test Report- AC": [
                "Switchyard Equipments",
                "Micom Relays",
                "Transformer IDT",
                "CT",
                "Relay",
                "Transformer",
                "Aux trafo",
                "Relay for RMU",
                "Battery charger",
                "Battery",
                "LA",
                "Isolater",
                "SCB",
                "Cables - AC",
                "Cables - DC",
                "Cables - control",
                "VCB",
                "Voltage and frequency meter",
                "Inverter",
            ],
            "Test Report- DC": [
                "Solar PV Module",
                "MMS (Column post, Rafter, Purlin)",
                "Transformer",
                "Strings Inverter",
                "Central Inverter",
                "AJB",
                "Solar LT Panel",
                "HT Panel",
                "MC4 /Y Connectors",
                "DC Cable",
                "AC Cable",
                "Equipment Calibration certificate",
                "Safety Manuals",
                "UPVC conduit",
                "CPVC Pipe / HDPE",
                "Communication cables",
                "UPS with battery and charger",
                "SCADA Panel",
                "Lightning Arrester",
                "Pre-fab structures",
                "Glands and Lugs",
                "Earth pit - ERT report",
                "MCS Pump motor",
                "Street light pole",
            ],
            "Earthing": [
                "Earthing Pit layout with number",
                "LA Pit drawing with identification numbers",
                "Earthing Details of Switchyard",
                "Earthing Pit Values - With grid & Without grid",
            ],
            "Mechanical": [
            "Structure detailed drawing",
            "Structure identification/layout Document",
            "Safety",
            "Safety alarm cabling layout Drawing",
            "Safety Alarm System installation drawing",
            "Fire Extinguisher Location identification, location, type, no",
            "Smoke alarm details",
        ],
        "Calculation - documents": [
            "CT & PT Calculation",
            "Battery and charger sizing Calculation",
            "Inverter clipping loss",
            "Shadow lossess",
        ],
        "Test certificate": [
    "CEIG Electrical inspector Approval Certificate for installation All AC Electrical equipments",
    "CEIG Electrical inspector Approval Certificate for installation All DC Equipments",
    "Dispatch & Inspection clearance certificate of metering CT",
    "Dispatch & Inspection clearance certificate of metering PT",
    "Transmission line approval",
    "Evacuation approval",
    "Synchronization Approval Letter",
    "HT cable jointer certificate",
],
"SCADA": [
    "WEATHER Station manual and details",
    "Pyranometer, Temp Sensor & module temp sensor",
    "Scada operation manual",
    "SCADA wiring Drawing",
    "Scada All report templates e.g DGR /Alarms pop ups / Real time data equipment wise",
    "Calibration Certificate",
    "Pyranometer",
    "Ambient temperature sensor",
    "Module temperature sensor",
    "Relays",
    "Any other items needing calibration",
    "Torque Wrench used for Tightness",
    "TS used for Piling / Foundation marking's",
],
"All Statutory Clearance/Compliances": [
    "Factory License",
    "Consent to operate",
    "Commissioning certificate",
    "Principal employer registration",
    "Labour License",
    "Fire Deptt NOC",
    "Borewell consent",
    "Gram Panchayat NOC",
    "Forest NOC",
    "Building stability test",
    "Civil Aviation NOC for TL",
    "PTCC",
    "Bay Allotment letter",
    "CEIG Approval for TL",
    "Synchronization Approval Letter",
    "Sector 68/164",
    "SLDC communication Scheme approval",
    "Registration under contract labour regulations",
    "Ground water Clearance",
    "Environmental Clearance for MOES",
    "TFR/ grid connectivity letter",
],
"SOP/WI": [
    "Module Cleaning",
    "Module mounting",
],
"All Keys": [
    "Panel door key",
    "HT Breaker Key",
    "Battery charger key",
    "HT breaker switch key",
    "CRP panel key",
    "RMU handle",
    "WMS keys",
    "Keys for marshalling boxes, RMUs, Battery Charger, CT/PT JBs, Outdoor circuit Bkr, Metering panel",
],
"OTHERS": [
    "Asset List",
    "Pre commissioning report",
    "Identification and Traceability Records",
    "List of major suppliers",
    "Warranty Card/Documents for all equipment",
    "List of spare parts",
    "List of Consumables",
    "Trouble shooting manual for major equipment",
],
"Warranty Certificates": [
    "MMS",
    "Module",
    "Inverter",
    "LT Panel",
    "Communication Cable",
    "AC DC Cables",
    "Module PICC",
    "UPS warranty certificate after registering online",
    "Safety line",
    "SCADA Panel",
    "BOS Items",
],
"Project Checklists": [
    "Project Checklists- As per field check sheets",
    "HSE Checklists",
    "Spares List",
    "Shadow Analysis",
],
"Data Sheet": [
    "Inverters",
    "Transformers",
    "RMU",
    "ICOG",
    "CT",
    "PT",
    "VCB/ACB",
    "ABT Meter",
    "PV Modules",
    "Cables - String & LT",
    "Cables - HT",
    "BOM of all",
    "Vendor List and Contact Details for All equipment",
    "Vendor NOC",
    "Review of DGR in Scada monitoring",
    "Cable length Schedule (AC, DC, communication and OFC)",
    "Checklist - Electrical, Civil and Electrical",
    "Control cable schedule",
]


        }

        # Add categories and documents to the database
        for category_name, documents in categories_and_documents.items():
            # Get or create the category
            category, created = DocumentCategory.objects.get_or_create(name=category_name)
            if created:
                self.stdout.write(self.style.SUCCESS(f"Created category: {category_name}"))

            # Add documents to the category
            for doc_name in documents:
                Document.objects.create(category=category, name=doc_name)
                self.stdout.write(self.style.SUCCESS(f"Added document: {doc_name} under category: {category_name}"))

        self.stdout.write(self.style.SUCCESS("All categories and documents added successfully!"))