# Generated by Django 4.2.25 on 2025-10-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_module', '0003_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_users',
        ),
    ]
